services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: biblioteca_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=abc123.
    volumes:
      - biblioteca_data:/var/opt/mssql

volumes:
  biblioteca_data:  